parameters:
- name: connectedServiceName
  type: string

stages:
  - stage: AzureAdvisorRecommendations
    jobs:
      - job: AzureAdvisorRecommendations
        variables:
          - name: scriptsPath
            value: $(System.DefaultWorkingDirectory)/scripts
        steps:
        - checkout: self
          clean: true

        - task: AzurePowerShell@5
          inputs:
            azureSubscription: ${{ parameters.connectedServiceName }}
            ScriptType: FilePath
            scriptPath: $(scriptsPath)/helpers/Start-AzAdvisorRecommendationRefresh.ps1
            azurePowerShellVersion: latestVersion
            pwsh: true
          displayName: Refresh Azure Advisor Recommendations

        - task: AzurePowerShell@5
          inputs:
            azureSubscription: ${{ parameters.connectedServiceName }}
            ScriptType: FilePath
            scriptPath: $(scriptsPath)/helpers/New-MsGraphAuthorizationToken.ps1
            azurePowerShellVersion: latestVersion
            pwsh: true
          displayName: Generate Microsoft Graph Token

        - task: AzurePowerShell@5
          inputs:
            azureSubscription: ${{ parameters.connectedServiceName }}
            ScriptType: FilePath
            scriptPath: $(scriptsPath)/securityRecommendations/Remove-DeprecatedOwnersFromSubscription.ps1
            azurePowerShellVersion: latestVersion
            pwsh: true
            scriptArguments: >
              -GraphToken "$(graphToken)"
          displayName: Security Recommendation - Deprecated accounts with owner permissions should be removed from your subscriptions

        - task: AzurePowerShell@5
          inputs:
            azureSubscription: ${{ parameters.connectedServiceName }}
            ScriptType: FilePath
            scriptPath: $(scriptsPath)/securityRecommendations/Remove-DeprecatedAccountFromSubscription.ps1
            azurePowerShellVersion: latestVersion
            pwsh: true
            scriptArguments: >
              -GraphToken "$(graphToken)"
          displayName: Security Recommendation - Deprecated accounts should be removed from your subscription